src/bot/urls.py
from django.urls import path
from django.views.decorators.csrf import csrf_exempt

from bot.views import BotUpdateView

urlpatterns = [
    path("webhook", csrf_exempt(BotUpdateView.as_view())),
]

src/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from users.sites import CustomOTPAdminSite

admin.site.__class__ = CustomOTPAdminSite

urlpatterns = [
    path("users/", include("users.urls"), name="users"),
    path("bot/", include("bot.urls"), name="bot"),
    path("admin/", admin.site.urls),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/users/urls.py
from django.urls import path

from users.views import PasswordSetView

app_name = "users"

urlpatterns = [
    path(
        "set_password/<uidb64>/<token>/",
        PasswordSetView.as_view(),
        name="password_set",
    ),
]

src/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils.translation import gettext_lazy as _

from .manager import UserManager


class User(AbstractUser):
    """User's model."""

    class UserRole(models.TextChoices):
        """Supporting model to make Choices field."""

        ADMIN = "main_admin", _("Администратор")
        REGION_ADMIN = "region_admin", _("Региональный администратор")

    username = None
    first_name = models.CharField(
        max_length=50, verbose_name="Имя пользователя"
    )
    last_name = models.CharField(
        max_length=50, verbose_name="Фамилия пользователя"
    )
    email = models.EmailField(
        unique=True, verbose_name="Адрес электронной почты"
    )

    objects = UserManager()

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

src/users/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.hashers import make_password
from django.db import transaction
from django.utils.translation import gettext_lazy as _
from django.utils.translation import ngettext_lazy
from django_otp.forms import OTPAuthenticationFormMixin
from django_otp.plugins.otp_email.models import EmailDevice

from users.models import User
from users.utils.users.registration import generate_random_password


class UserCreationForm(forms.ModelForm):
    """A form for creating new users with random password."""

    class Meta:
        model = User
        fields = ("email", "first_name", "last_name")

    def save(self, commit=True):
        """Save new user to db with random password."""
        user = super().save(commit=False)
        user.password = make_password(generate_random_password())
        if commit:
            user.save()
        return user


class UserChangeForm(forms.ModelForm):
    """A form for updating users."""

    class Meta:
        model = User
        fields = (
            "email",
            "first_name",
            "last_name",
            "is_active",
            "is_superuser",
        )


class CustomOTPAuthenticationFormMixin(OTPAuthenticationFormMixin):
    """Customized OTPAuthenticationFormMixin mixin."""

    otp_error_messages = {
        "token_required": _("Пожалуйста, введите одноразовый код."),
        "challenge_exception": _("Ошибка генерации кода: {0}"),
        "not_interactive": _("Код не может быть отправлен."),
        "challenge_message": _("Код отправлен на указанную почту."),
        "invalid_token": _("Неверный код. Проверьте правильность."),
        "n_failed_attempts": ngettext_lazy(
            "Допущено %(failure_count) ошибок. Доступ временно ограничен.",
            "Допущено %(failure_count) ошибок. Доступ временно ограничен.",
            "failure_count",
        ),
        "verification_not_allowed": _("Верификация недоступна"),
    }

    def clean_otp(self, user):
        """Perform OTP clean."""
        if user is None:
            return

        validation_error = None
        with transaction.atomic():
            try:
                device = self._chosen_device(user)
                token = self.cleaned_data.get("otp_token")

                user.otp_device = None

                try:
                    if self.cleaned_data.get("otp_challenge"):
                        self._handle_challenge(device)
                    elif token:
                        user.otp_device = self._verify_token(
                            user, token, device
                        )
                    else:
                        self._handle_challenge(device)
                        raise forms.ValidationError(
                            self.otp_error_messages["token_required"],
                            code="token_required",
                        )
                finally:
                    if user.otp_device is None:
                        self._update_form(user)
            except forms.ValidationError as e:
                # Validation errors shouldn't abort the transaction, so we have
                # to carefully transport them out.
                validation_error = e

        if validation_error:
            raise validation_error

    def _chosen_device(self, user):
        """Return EmailDevise as default."""
        return EmailDevice.objects.filter(user=user).first()


class CustomOTPAuthenticationForm(
    CustomOTPAuthenticationFormMixin, AuthenticationForm
):
    """Customized OTPAuthenticationForm form."""

    otp_token = forms.CharField(
        required=False, widget=forms.TextInput(attrs={"autocomplete": "off"})
    )

    otp_challenge = forms.CharField(required=False)

    def clean(self):
        """Clean form data."""
        self.cleaned_data = super().clean()
        self.clean_otp(self.get_user())

        return self.cleaned_data

src/users/views.py
from django.contrib import messages
from django.contrib.auth.views import PasswordResetConfirmView
from django.urls import reverse_lazy


class PasswordSetView(PasswordResetConfirmView):
    """User password reset view."""

    success_url = reverse_lazy("admin:index")
    template_name = "authentication/password_set_confirm.html"

    def form_valid(self, form):
        """Set user satus as active if password was changed."""
        response = super().form_valid(form)
        messages.success(self.request, "Пароль был успешно изменен.")
        self.user.is_staff = True
        self.user.save()
        return response

src/users/templates/authentication/login.html
{% extends "admin/base_site.html" %}
{% load i18n static %}

{% block extrastyle %}
    {{ block.super }}
    <link rel="stylesheet" type="text/css" href="{% static "admin/css/login.css" %}" />
    {{ form.media }}

    <style type="text/css">
        input#id_otp_token,
        select#id_otp_device
        {
            clear: both;
            padding: 6px;
            width: 100%;
            -webkit-box-sizing: border-box;
            -moz-box-sizing: border-box;
                    box-sizing: border-box;
        }
    </style>
{% endblock %}

{% block bodyclass %}{{ block.super }} login{% endblock %}

{% block usertools %}{% endblock %}

{% block nav-global %}{% endblock %}

{% block content_title %}{% endblock %}

{% block breadcrumbs %}{% endblock %}

{% block nav-sidebar %}{% endblock %}

{% block content %}
{% if form.errors and not form.non_field_errors %}
<p class="errornote">
{% if form.errors.items|length == 1 %}{% trans "Please correct the error below." %}{% else %}{% trans "Please correct the errors below." %}{% endif %}
</p>
{% endif %}

{% if form.non_field_errors %}
{% for error in form.non_field_errors %}
<p class="errornote">
    {{ error }}
</p>
{% endfor %}
{% endif %}

<div id="content-main">

{% if user.is_authenticated %}
<p class="errornote">
{% blocktrans trimmed %}
    You are authenticated as {{ username }}, but are not authorized to
    access this page. Would you like to login to a different account?
{% endblocktrans %}
</p>
{% endif %}

<form action="{{ app_path }}" method="post" id="login-form">{% csrf_token %}
  <div class="form-row">
    {{ form.username.errors }}
    {{ form.username.label_tag }} {{ form.username }}
  </div>
  <div class="form-row">
    {{ form.password.errors }}
    {{ form.password.label_tag }} {{ form.password }}
    <input type="hidden" name="next" value="{{ next }}" />
  </div>
  {% if form.get_user %}
  <div class="form-row">
    {{ form.otp_token.errors }}
    <label for="id_otp_token" class="required">{% trans 'Одноразовый код:' %}</label> {{ form.otp_token }}
  </div>
  {% endif %}
  {% url 'admin_password_reset' as password_reset_url %}
  {% if password_reset_url %}
  <div class="password-reset-link">
    <a href="{{ password_reset_url }}">{% trans 'Forgotten your password or username?' %}</a>
  </div>
  {% endif %}
  <div class="submit-row">
    <label>&nbsp;</label><input type="submit" value="{% trans 'Log in' %}" />
    {% if form.get_user %}
    <label>&nbsp;</label><input type="submit" name="otp_challenge" value="{% trans 'Отправить код еще раз' %}" />
    {% endif %}
  </div>
</form>

<script type="text/javascript">
document.getElementById('id_username').focus()
</script>
</div>
{% endblock %}

src/users/templates/authentication/password_set_confirm.html
{% extends "admin/base_site.html" %}
{% load i18n static %}

{% block extrastyle %}
{{ block.super }}
<link rel="stylesheet" type="text/css"
      href="{% static 'admin/css/login.css' %}"/>
{{ form.media }}

<style type="text/css">
    input#id_otp_token,
    select#id_otp_device
    {
        clear: both;
        padding: 6px;
        width: 100%;
        -webkit-box-sizing: border-box;
        -moz-box-sizing: border-box;
                box-sizing: border-box;
    }
</style>
{% endblock %}

{% block bodyclass %}{{ block.super }} login{% endblock %}

{% block branding %}
<h1 id="site-name"><a href="{% url 'admin:index' %}">Новый пароль</a></h1>
{% if user.is_anonymous %}
  {% include "admin/color_theme_toggle.html" %}
{% endif %}
{% endblock %}

{% block usertools %}{% endblock %}

{% block nav-global %}{% endblock %}

{% block content_title %}{% endblock %}

{% block breadcrumbs %}{% endblock %}

{% block nav-sidebar %}{% endblock %}

{% block content %}

{% if validlink %}
<div class="main" id="main">
    <div id="content-start" class="content" tabindex="-1">
        <div id="content" class="colM">
            <div id="content-main">
                {% if user.is_authenticated %}
                <p class="errornote">
                    {% blocktrans trimmed %}
                    You are authenticated as {{ username }}, but are not
                    authorized to
                    access this page. Would you like to login to a
                    different account?
                    {% endblocktrans %}
                </p>
                {% endif %}

                {% include "includes/form_errors.html"%}
                <form method="post" id="login-form"
                      {% if action_url %}
                      action="{% url action_url %}"
                      {% endif %}
                >
                    {% include "includes/form.html"%}
                </form>

                <script type="text/javascript">
                    document.getElementById('id_username').focus()
                </script>
            </div>
            {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                <li {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
                {% endfor %}
            </ul>
            {% endif %}
            {% else %}
            <div class="row justify-content-center">
                <div class="col-md-8 p-5">
                    <div class="card">
                        <div class="card-header">Ошибка</div>
                        <div class="card-body">
                            <p>Ссылка установки пароля содержит ошибку или
                                устарела.</p>
                        </div>
                    </div>
                </div>
            </div>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}